version: "3.9"

volumes:
  storage:

services:
  proxy:
    build: ./Proxy
    ports:
      - "5000:80"

  web:
    build: ./App

  api:
    build: ./Backend
    environment:
        - ConnectionStrings__Default=Server=database;Port=5432;Database=helse;User Id=postgres;Password=postgres
        - Jwt__Issuer=test.com
        - Jwt__Audience=test.com
        - Jwt__Key=ffeyufegyvegiuegiygcyvgzyi

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: helse
      PG_DATA: /var/lib/postgresql/data


