version: "3.9"

volumes:
  storage:

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
        - ConnectionStrings__Default=Server=database;Port=5432;Database=helse;User Id=postgres;Password=postgres
        - Jwt__Issuer=test.com
        - Jwt__Audience=test.com
        - Jwt__Key=ffeyufegyvegiuegiygcyvgzyi

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: helse
      PG_DATA: /var/lib/postgresql/data
