services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: helse
    volumes:
      - pgdata:/var/lib/postgresql/
    ports:
      - 5432:5432

  gotify:
    image: gotify/server
    ports:
      - 5433:80
    environment:
      GOTIFY_DEFAULTUSER_PASS: 'admin'

volumes:
  pgdata:
 