targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/services/swagger/"
          output_folder: "lib/services/swagger/generated_code/"
          input_urls:
            - url: http://localhost:5059/swagger/v1/swagger.json