CREATE TABLE health.MetricGroup (
    Id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Name VARCHAR Not NULL,
    Description VARCHAR NOT NULL,
    ShowTitle BOOL NOT NULL DEFAULT false,
    ShowOnDashboard BOOL NOT NULL DEFAULT false
);

INSERT INTO
    health.MetricGroup(
        id,
        name,
        description,
        showtitle,
        showOndashboard
    )
VALUES
    (1, 'Other', '', false, false),
    (2, 'Measure', '', false, true),
    (3, 'Women Health', '', true, false),
    (4, 'Activity', '', true, true);

ALTER TABLE
    health.MetricType
ADD
    COLUMN GroupId BIGINT NOT NULL DEFAULT 1;

ALTER TABLE
    health.MetricType
ADD
    COLUMN ShowOnDashboard BOOL NOT NULL DEFAULT true;

ALTER TABLE
    health.MetricType
ADD
    CONSTRAINT FK_EventType_TO_Group FOREIGN KEY (GroupId) REFERENCES health.MetricGroup (Id);

UPDATE
    health.MetricType
SET
    GroupId = 2
WHERE
    Id IN(1, 2, 3, 4, 5)
    AND UserEditable IS false;

UPDATE
    health.MetricType
SET
    GroupId = 3
WHERE
    Id IN(9, 10, 11, 16)
    AND UserEditable IS false;

UPDATE
    health.MetricType
SET
    GroupId = 4
WHERE
    Id IN(6, 7, 8)
    AND UserEditable IS false;

UPDATE
    health.MetricType
SET
    ShowOnDashboard = true
WHERE
    Id IN(1, 2, 3, 4, 6, 7)
    AND UserEditable IS false;