CREATE TABLE health.EventGroup (
    Id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Name VARCHAR Not NULL,
    Description VARCHAR NOT NULL,
    ShowTitle BOOL NOT NULL DEFAULT false,
    ShowOnDashboard BOOL NOT NULL DEFAULT false
);

INSERT INTO
    health.MetricType(id, name, description, showtitle, showOndashboard)
VALUES
    (1, 'Other', '', false, false),
    (2, 'Measure', '', false, true),
    (3, 'Women Health', true, true),
    (4, 'Activity', true, true);

ALTER TABLE
    health.MetricType
ADD
    COLUMN GroupId BIGINT NOT NULL DEFAULT 1;

ALTER TABLE
    health.MetricType
ADD
    COLUMN ShowOnDashboard BOOL NOT NULL DEFAULT false;

ALTER TABLE
    health.MetricType
ADD
    CONSTRAINT FK_EventType_TO_Group FOREIGN KEY (GroupId) REFERENCES health.EventGroup (Id);