CREATE SCHEMA person;

CREATE TABLE person.Address
(
  Id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  PersonId BIGINT  NOT NULL,
  Street   VARCHAR NULL    ,
  Number   VARCHAR NULL    ,
  Postal   VARCHAR NULL    ,
  Country  CHAR    NULL    
);

CREATE TABLE person.Person
(
  Id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  Name       VARCHAR NULL    ,
  Surname    VARCHAR NULL    ,
  Identifier VARCHAR NULL ,
  Birth      DATE    NULL    
);

CREATE TABLE person.Right
(
  Id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  PersonId BIGINT   NULL    ,
  UserId   BIGINT   NOT NULL,
  Start    TIMESTAMP NOT NULL,
  Stop      TIMESTAMP NULL    ,
  Type     INT      NOT NULL
);


CREATE TABLE person.User
(
  Id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  PersonId   BIGINT  NOT NULL,
  Identifier VARCHAR NOT NULL,
  Password   VARCHAR NOT NULL,
  Type       INT     NOT NULL,
  Email      VARCHAR NULL    ,
  Phone      VARCHAR NULL   
);

ALTER TABLE person.Right
  ADD CONSTRAINT FK_Person_TO_Right
    FOREIGN KEY (PersonId)
    REFERENCES person.Person (Id);

ALTER TABLE person.Right
  ADD CONSTRAINT FK_User_TO_Right
    FOREIGN KEY (UserId)
    REFERENCES person.User (Id);

ALTER TABLE person.User
  ADD CONSTRAINT FK_Person_TO_User
    FOREIGN KEY (PersonId)
    REFERENCES person.Person (Id);

ALTER TABLE person.Address
  ADD CONSTRAINT FK_Person_TO_Address
    FOREIGN KEY (PersonId)
    REFERENCES person.Person (Id);

