CREATE SCHEMA Common;

CREATE TABLE Common.Units (
    Id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Code VARCHAR NOT NULL,
    Description VARCHAR NULL,
    Type INT NOT NULL,
    BaseUnit INT NULL,
    ConversionFactor NUMERIC NULL,
    Formula VARCHAR NULL,
    CONSTRAINT FK_Units_To_Units FOREIGN KEY (BaseUnit) REFERENCES Common.Units (Id)
);

INSERT INTO
    Common.Units (
        Id,
        Code,
        Description,
        Type,
        BaseUnit,
        ConversionFactor
    )
VALUES
    (0, '', 'None', 0, null, null),
    (1, 'm', 'Meter', 1, null, null),
    (2, 'cm', 'Centimeter', 1, 1, 0.01),
    (3, 'mm', 'Millimeter', 1, 1, 0.001),
    (4, 'km', 'Kilometer', 1, 1, 1000),
    (5, 'g', 'Gram', 2, null, null),
    (6, 'kg', 'Kilogram', 2, 5, 1000),
    (7, 'mg', 'Milligram', 2, 5, 0.001),
    (8, 'bpm', 'BPM', 3, null, null),
    (9, 'C', 'Celsius', 4, null, null),
    (10, 'kcal', 'Calories', 5, null, null),
    (11, '%', 'Percent', 6, null, null)
;

ALTER TABLE
    Health.Metric
ADD
    COLUMN Unit INT NULL;

ALTER TABLE
    Health.Metric
ADD
    CONSTRAINT FK_Metric_To_Units FOREIGN KEY (Unit) REFERENCES Common.Units (Id);

ALTER TABLE
    Health.MetricType DROP COLUMN Unit;

ALTER TABLE
    Health.MetricType
ADD
    COLUMN Unit INT NOT NULL DEFAULT 0;

ALTER TABLE
    Health.MetricType
ADD
    CONSTRAINT FK_MetricType_To_Units FOREIGN KEY (Unit) REFERENCES Common.Units (Id);

UPDATE Health.MetricType SET Unit = 8 WHERE Id = 1;
UPDATE Health.MetricType SET Unit = 11 WHERE Id = 2;
UPDATE Health.MetricType SET Unit = 6  WHERE Id = 3;
UPDATE Health.MetricType SET Unit = 2 WHERE Id = 4;
UPDATE Health.MetricType SET Unit = 9 WHERE Id = 5;
UPDATE Health.MetricType SET Unit = 10 WHERE Id = 7;
UPDATE Health.MetricType SET Unit = 1 WHERE Id = 8;
UPDATE Health.MetricType SET Unit = 2 WHERE Id = 17;