-- remove the existing file tables
ALTER TABLE
    health.Event 
    DROP CONSTRAINT FK_Files_TO_Event,
    DROP CONSTRAINT fk_treatment_to_event;

DROP TABLE health.Treatment;
DROP TABLE health.prescription;
DROP TABLE file.Blob;
DROP TABLE file.Files;

ALTER TABLE
    Health.Event DROP COLUMN FileId;

-- add the new file tables
CREATE TABLE file.Files (
    Id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Created TIMESTAMP NOT NULL,
    Data bytea NOT NULL,
    DataType VARCHAR NOT NULL,
    Type INT NOT NULL,
    Name VARCHAR NOT NULL,
    Description VARCHAR NOT NULL,
    Start TIMESTAMP NOT NULL,
    Stop TIMESTAMP NULL,
    PersonId BIGINT NOT NULL REFERENCES person.Person (Id)
);

CREATE TABLE health.MetricFiles (
    FileId BIGINT NOT NULL REFERENCES file.Files (Id),
    MetricId BIGINT NOT NULL REFERENCES health.Metric(Id),
    Created TIMESTAMP NOT NULL,
    PRIMARY KEY(FileId, MetricId)
);

CREATE TABLE health.EventFiles (
    FileId BIGINT NOT NULL REFERENCES file.Files (Id),
    EventId BIGINT NOT NULL REFERENCES health.Event(Id),
    Created TIMESTAMP NOT NULL,
    PRIMARY KEY(FileId, EventId)
);