name: Build Android
on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
      push:
        required: true
        type: boolean
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v4.1.4
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2.14.0
      with:
         channel: 'beta'
         # Enables cache for flutter packages              
         # Speed up the process
         cache: true
         
     # Get Flutter project dependencies
    - name: Get dependencies
      run: flutter pub get
      working-directory: 'App'
      
    - name: Build release app bundle
      run: flutter build apk --release --split-per-abi
      working-directory: 'App'   

    - name: Finding binaries files
      if: ${{ inputs.push }}
      id: finding-files        
      run: |
        {
          cd build/app/outputs/flutter-apk
          echo 'FILELIST<<EOF'
          find . -name '*-release.apk' -print 
          echo EOF
        } >> "$GITHUB_ENV"
        
    - name: Upload binaries to release
      if: ${{ inputs.push }}
      run: |
        for i in $FILELIST; do        
          gh release upload ${{github.event.release.tag_name}} ${i}   
        done  
      env:
        GH_TOKEN: ${{ github.token }}
    
      
