name: Build Android
on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
      push:
        required: true
        type: boolean
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v4.1.4
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2.14.0
      with:
         channel: 'beta'
         # Enables cache for flutter packages              
         # Speed up the process
         cache: true
         
     # Get Flutter project dependencies
    - name: Get dependencies
      run: flutter pub get
      working-directory: 'App'
      
    - name: Build release app bundle
      run: flutter build appbundle
      working-directory: 'App'

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      if: ${{ inputs.push }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: App/build/app/outputs/bundle/release/app-release.aab
        asset_name: "app_bundle.aap"
        tag: ${{ inputs.tag }}
    
      