name: Build Android
on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
      sign:
        required: true
        type: boolean
      upload:
        required: true
        type: boolean
      mode:
        required: false
        type: string
        default: release
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PROPERTIES_PATH: "flutter_frontend/android/key.properties"
  
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v6.0.2

    - uses: actions/setup-java@v5.2.0
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2.14.0
      id: flutter-action
      with:
        channel: stable
        cache: true
        flutter-version: '3.44.4'
        
    - name: Decoding base64 key into a file
      if: ${{ inputs.sign }}
      run: echo ${{ secrets.KEY_FILE }} | base64 --decode > flutter_frontend/android/app/key.jks
    
    - name: Build release app bundle
      env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_STORE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PATH: key.jks
      run: flutter build apk --${{inputs.mode}} --split-per-abi --split-debug-info=build/symbols
      working-directory: 'flutter_frontend'   

    - name: Rename APK Artifacts
      run: |        
          cd flutter_frontend/build/app/outputs/flutter-apk          
          find . -name '*-release.apk' -print 
          mv app-armeabi-v7a-release.apk helse-v${{ github.event.inputs.version }}-armeabi-v7a.apk
          mv app-arm64-v8a-release.apk helse-v${{ github.event.inputs.version }}-arm64-v8a.apk
          mv app-x86_64-release.apk helse-v${{ github.event.inputs.version }}-x86_64.apk        

    - name: Finding binaries files
      if: ${{ inputs.push }}
      id: finding-files        
      run: |
        {
          cd flutter_frontend/build/app/outputs/flutter-apk
          echo 'FILELIST<<EOF'
          find . -name '*-release.apk' -print 
          echo EOF
        } >> "$GITHUB_ENV"

    - name: Upload artefact
      if: ${{ inputs.push }}
      uses: actions/upload-artifact@v7.0.1   
      with:
        path: flutter_frontend/build/app/outputs/flutter-apk/*-arm64-v8a-release.apk
        archive: false
        if-no-files-found: error
      
    - name: Upload binaries to release
      if: ${{ inputs.upload }}
      run: |
        cd flutter_frontend/build/app/outputs/flutter-apk
        for i in $FILELIST; do        
          gh release upload ${{github.event.release.tag_name}} ${i}   
        done  
      env:
        GH_TOKEN: ${{ github.token }}
    
      
