name: Docker Image CD

on:
  push:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker
        uses: ./.github/workflows/build-android.yml

  build-docker:
    runs-on: ubuntu-latest        
    steps:
      - name: Build docker
        uses: ./.github/workflows/build-docker.yml
        with:
          push: true
