name: CD

on:
  push:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-android:
    permissions:
      contents: read 
    uses: ./.github/workflows/build-android.yml
    secrets: inherit

  build-docker:
    permissions:
      contents: read 
      packages: write
    uses: ./.github/workflows/build-docker.yml
    with:
      push: true
