name: Docker Image CD

on:
  push:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-android:
    uses: ./.github/actions/build-android.yml

  build-docker:
    uses: ./.github/actions/build-docker.yml
    with:
      push: true
