name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs: 
  build-android:
    permissions:
      contents: read 
    uses: ./.github/workflows/build-android.yml
    with:
      push: false

  build-docker:
    permissions:
      contents: read 
    uses: ./.github/workflows/build-docker.yml
    with:
      push: false
      tags: ci
      labels: ci
