name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:   
      - name: Build docker
        uses: ./.github/workflows/build-docker.yml
        with:      
          push: false
          tags: ci
          labels: ci
