name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs: 
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker
        uses: ./.github/actions/build-android

  build-docker:
    runs-on: ubuntu-latest    
    permissions:
      contents: read
      packages: write      
    steps:   
      - uses: actions/checkout@v3

      - name: Build docker
        uses: ./.github/actions/build-docker
        with:      
          push: false
          tags: ci
          labels: ci
