name: Release

on:
 release:

jobs:
  build-android:
    permissions:
      contents: write 
    uses: ./.github/workflows/build-android.yml
    with:
        push: true
        tag: ${{ github.ref }}

  build-docker:
    permissions:
      contents: read 
      packages: write
    uses: ./.github/workflows/build-docker.yml
    with:
      push: true
   
