name: Release

on:
 release:
    types: created

jobs:
  build-android:
    permissions:
      contents: write 
    uses: ./.github/workflows/build-android.yml
    with:
        push: true
        sign: true
        upload: true
    secrets: inherit

  build-docker:
    permissions:
      contents: read 
      packages: write
    uses: ./.github/workflows/build-docker.yml
    with:
      push: true
   
