name: Release

on:
  release:
    types: [published]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker
        uses: ./.github/workflows/build-android.yml

  build-docker:
    runs-on: ubuntu-latest        
    steps:
      - name: Build docker
        uses: ./.github/workflows/build-docker.yml
        with:
          push: true