name: Release

on:
  release:
    types: [published]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker
        uses: ./.github/actions/build-android

  build-docker:
    runs-on: ubuntu-latest        
    steps:
      - name: Build docker
        uses: ./.github/actions/build-docker
        with:
          push: true